const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.Play
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{ScrollTo: 0},
	{spr_player: 0},
	{Mouse: 0},
	{MoveTo: 0},
	{spr_enemy: 0},
	{ID: 0},
	{spr_spawner: 0},
	{Bullet: 0},
	{DestroyOutside: 0},
	{spr_bullet: 0},
	{Hud1_enc: 0},
	{Txt_kills: 0},
	{Txt_level: 0},
	{Txt_timer: 0},
	{Sine: 0},
	{bomba: 0},
	{bomba2: 0},
	{Txt_bombahud2: 0},
	{tb_Flash: 0},
	{Particles: 0},
	{spr_inimigo2: 0},
	{Text: 0},
	{cont_regres: 0},
	{GameOver_scren: 0},
	{txt_GameOver: 0},
	{txt_GameOver2: 0},
	{Keyboard: 0},
	{Txt_killsMAX: 0},
	{LocalStorage: 0},
	{Spr_Mira: 0},
	{Audio: 0},
	{spawnSpeed: 0},
	{velocidadeInimigo: 0},
	{spawnerRNG: 0},
	{score: 0},
	{level: 0},
	{timer: 0},
	{bombas: 0},
	{GameOver: 0},
	{crono_regressiva: 0},
	{HP: 0},
	{hiScore: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	spr_player: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	spr_enemy: class extends self.ISpriteInstance {},
	spr_spawner: class extends self.ISpriteInstance {},
	spr_bullet: class extends self.ISpriteInstance {},
	Hud1_enc: class extends self.ITiledBackgroundInstance {},
	Txt_kills: class extends self.ITextInstance {},
	Txt_level: class extends self.ITextInstance {},
	Txt_timer: class extends self.ITextInstance {},
	bomba: class extends self.ISpriteInstance {},
	bomba2: class extends self.ISpriteInstance {},
	Txt_bombahud2: class extends self.ITextInstance {},
	tb_Flash: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	spr_inimigo2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	cont_regres: class extends self.ITextInstance {},
	GameOver_scren: class extends self.ITiledBackgroundInstance {},
	txt_GameOver: class extends self.ITextInstance {},
	txt_GameOver2: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Txt_killsMAX: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Spr_Mira: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}